server:
  port: 8081

spring:
  application:
    name: INVENTORY-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: Kinu@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    function:
      definition: productInventoryConsumer;userDeletedConsumer;orderCancelledConsumer

    stream:
      bindings:

        productInventoryConsumer-in-0:
          destination: product-inventory-topic
          group: inventory-product-group
          content-type: application/json

        userDeletedConsumer-in-0:
          destination: user-deleted-inventory
          group: inventory-service

        orderCancelledConsumer-in-0:
          destination: order-cancelled
          group: inventory-service

        lowStockAlert-out-0:
          destination: low-stock-topic
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s